# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        jwt_user_provider:
            id: jwt_user_provider

    firewalls:
        jwt_secured_area:
            pattern: "^/app/"
            stateless: true
            simple_preauth:
                authenticator: jwt_authenticator
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
